// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow that suggests logical connections between tasks based on a high-level prompt.
 *
 * - suggestTaskConnections - A function that handles the task connection suggestion process.
 * - SuggestTaskConnectionsInput - The input type for the suggestTaskConnections function.
 * - SuggestTaskConnectionsOutput - The return type for the suggestTaskConnections function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTaskConnectionsInputSchema = z.object({
  prompt: z.string().describe('A high-level prompt describing the project or tasks.'),
});
export type SuggestTaskConnectionsInput = z.infer<typeof SuggestTaskConnectionsInputSchema>;

const SuggestTaskConnectionsOutputSchema = z.object({
  connections: z
    .array(
      z.object({
        source: z.string().describe('The source task node ID.'),
        target: z.string().describe('The target task node ID.'),
        label: z.string().optional().describe('A label describing the connection.'),
      })
    )
    .describe('An array of suggested task connections.'),
});
export type SuggestTaskConnectionsOutput = z.infer<typeof SuggestTaskConnectionsOutputSchema>;

export async function suggestTaskConnections(input: SuggestTaskConnectionsInput): Promise<SuggestTaskConnectionsOutput> {
  return suggestTaskConnectionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTaskConnectionsPrompt',
  input: {schema: SuggestTaskConnectionsInputSchema},
  output: {schema: SuggestTaskConnectionsOutputSchema},
  prompt: `You are a project planning assistant. Given the following project description, suggest logical connections between tasks.

Project Description: {{{prompt}}}

Suggest connections between tasks, including source task ID, target task ID, and a label describing the connection.
Return the connections as a JSON array.

Example:
[
  {
    "source": "task1",
    "target": "task2",
    "label": "Depends on"
  },
  {
    "source": "task3",
    "target": "task1",
    "label": "Workflow"
  }
]
`,
});

const suggestTaskConnectionsFlow = ai.defineFlow(
  {
    name: 'suggestTaskConnectionsFlow',
    inputSchema: SuggestTaskConnectionsInputSchema,
    outputSchema: SuggestTaskConnectionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
